#!/usr/bin/env python3
"""Generate the check reference from the cartridge's own registry.

The cartridge prints a stable code with every failure and a URL whose anchor is
that code. Those anchors have to exist, and they have to say the same thing the
ROM said -- a documentation page that has drifted from the ROM is worse than no
page, because a reader who followed the link has already trusted it.

So the page is generated from `src/registry.asm`, which is where the codes,
names and one-line explanations already live, and `--check` fails if a
committed page no longer matches. Python standard library only, like everything
else here.

    tools/gen-docs.py                write docs/CHECKS.md
    tools/gen-docs.py --check        fail if it is out of date
    tools/gen-docs.py -o PATH        write somewhere else (TerminalGB's copy)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "src" / "registry.asm"

PREAMBLE = """<!-- Generated by tools/gen-docs.py from src/registry.asm. Do not edit by hand. -->
# GBSelfTest check reference

Every check this cartridge runs has a **stable code**. The code is printed with
the failure, it is the anchor on this page, and it never changes meaning: codes
are not reused and not renumbered, so one from an old run still means what it
meant.

A failure looks like this over the link port:

```
GB-PPU-08 FAIL objects on a line lengthen mode 3
      got $0000  want $000F
      -> ten objects on a line did not lengthen mode 3. Each one stops the
         background fetcher for at least six cycles while its own row is
         fetched; a renderer that draws the line in one go and charges a fixed
         172 cycles reports no penalty at all
      -> https://github.com/Alchemy86/TerminalGB/blob/main/docs/gbselftest.md#gb-ppu-08
```

The `->` lines are the point. Any suite can print `FAIL`; what an emulator
author needs is a hypothesis about *what behaviour is missing* and somewhere to
read about it.

## What the verdicts mean

| verdict | meaning |
|---|---|
| `ok` | the machine did what the check expected |
| `FAIL` | it did not, and the explanation says what was expected and why |
| `skip` | the check does not apply to this machine, or a prerequisite for measuring it was not available. A skip is counted separately and is never a pass |

The last line of the report is `Passed` or `Failed`, which is Blargg's
convention: every existing Game Boy test runner already understands those two
words, so this cartridge needs no new host support.

## How to read a run

The areas run in the order below and it is not alphabetical. The processor
comes first because everything under it is written in instructions; the clocks
come next because every timing measurement is expressed in them; the display
and the sound chip come last because their checks are built on both. **A
failure high up can cascade** -- a broken `INC HL` would make the model the
adder is checked against wrong too. Fix the first failure first.

"""

POSTAMBLE = """
## Where this cartridge is thin on purpose

It is a first-response cartridge: broad, fast, self-explaining, one file. It is
not a replacement for the suites that go deep, and it says so in its own
coverage statement at the end of every run:

| for | use |
|---|---|
| exhaustive instruction sweeps | Blargg's `cpu_instrs` |
| cycle-exact edges in the timer and the display | the Mooneye test suite |
| the sound chip in detail | SameSuite, and Blargg's `dmg_sound` |
| pixel-exact rendering | the Mealybug Tearoom tests, which need a host and a reference image |
| mappers in detail | the MBC test suites |

## What a cartridge structurally cannot check

* **The composited picture.** There is no framebuffer to read: the display
  streams pixels to the panel and keeps none of them. What *is* checked here is
  the rendering **fingerprint** -- mode 3 lasts exactly as long as the fetcher
  takes, so a scene whose cost is documented can be laid out and the length
  measured.
* **Anything finer than four dots.** The processor can only observe on machine
  cycle boundaries, and a machine cycle is four dots.
* **Sound as sound.** Register behaviour and the length counter are checked;
  what comes out of the speaker is not.
"""


def parse_registry(text: str) -> tuple[list[dict], dict[str, str]]:
    """Return the areas in run order, and every string label's contents."""
    strings: dict[str, str] = {}
    for m in re.finditer(r'^(\w+):\s*db "((?:[^"\\]|\\.)*)",0\s*$', text, re.M):
        strings[m.group(1)] = m.group(2)

    areas = []
    for m in re.finditer(r"^\s*area (\w+), (\w+), (\w+), (\w+), (\d+)\s*$", text, re.M):
        areas.append(
            {
                "name": strings.get(m.group(1), m.group(1)),
                "prefix": strings.get(m.group(2), m.group(2)),
                "list": m.group(3),
                "checks": [],
            }
        )

    for area in areas:
        block = re.search(
            r"^%s:\n(.*?)^\s*dw 0\s*$" % re.escape(area["list"]),
            text,
            re.M | re.S,
        )
        if not block:
            raise SystemExit(f"cannot find the check list {area['list']}")
        for c in re.finditer(
            r"^\s*check (\w+),\s*(\d+),\s*(\w+),\s*(\w+)\s*$", block.group(1), re.M
        ):
            area["checks"].append(
                {
                    "routine": c.group(1),
                    "number": int(c.group(2)),
                    "name": strings.get(c.group(3), c.group(3)),
                    "explain": strings.get(c.group(4), c.group(4)),
                }
            )
    return areas, strings


BODY_BEGIN = "<!-- checks:begin -->"
BODY_END = "<!-- checks:end -->"


def render(areas: list[dict], body_only: bool = False) -> str:
    # The per-code sections are fenced by markers so that a consuming project
    # can splice exactly them into a page of its own without guessing where the
    # framing prose ends.
    out = [] if body_only else [PREAMBLE]
    out.append(BODY_BEGIN + "\n")
    for area in areas:
        title = area["name"]
        out.append(f"## {title}\n")
        for chk in area["checks"]:
            code = f"GB-{area['prefix']}-{chk['number']:02d}"
            out.append(f"### {code}\n")
            out.append(f"**{chk['name']}**\n")
            out.append(f"{chk['explain']}.\n")
    out.append(BODY_END + "\n")
    if not body_only:
        out.append(POSTAMBLE)
    return "\n".join(out).replace("\n\n\n", "\n\n")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if out of date")
    ap.add_argument(
        "--body-only",
        action="store_true",
        help="emit only the per-code sections, for splicing into a page that "
        "has its own framing -- which is how the consuming project's copy is "
        "kept in step without duplicating the prose",
    )
    ap.add_argument("-o", "--out", default=str(ROOT / "docs" / "CHECKS.md"))
    args = ap.parse_args(argv)

    areas, _ = parse_registry(REGISTRY.read_text())
    total = sum(len(a["checks"]) for a in areas)
    if total == 0:
        raise SystemExit("no checks found; the registry format must have moved")
    page = render(areas, body_only=args.body_only)

    out = Path(args.out)
    if args.check:
        if not out.exists() or out.read_text() != page:
            print(f"{out} is out of date; run tools/gen-docs.py", file=sys.stderr)
            return 1
        print(f"{out} matches the registry ({total} checks)")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page)
    print(f"wrote {out} ({total} checks in {len(areas)} areas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
