#!/bin/sh
# Run the cartridge on every implementation the README quotes, and print the
# table it quotes them in.
#
# The spread this produces is the property the cartridge exists to have: a
# careful emulator and a rough one must not get the same score, or the suite is
# measuring nothing. It is not a league table. Every implementation here is
# doing what it set out to do, and two of the three name their approximations
# in their own documentation before this cartridge ever found them.
#
#   tools/scoreboard.sh              print the page
#   tools/scoreboard.sh --write      write docs/scoreboard.md, and splice the
#                                    same table into README.md
#
# Needs a C compiler (SameBoy, Peanut-GB) and a Rust toolchain (TerminalGB).
# Each runner fetches and pins its own emulator; nothing is vendored here.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
FRAMES="${FRAMES:-4000}"
WRITE=0
[ "${1:-}" = "--write" ] && WRITE=1
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# "TOTAL 84/87 checks, 3 skipped" -> "84 / 87, 3 skipped".
row() {  # row <report-file>
    total=$(grep -m1 '^TOTAL ' "$1" | tr -d '\r')
    score=$(echo "$total" | sed -n 's|^TOTAL \([0-9]*\)/\([0-9]*\) .*|\1 / \2|p')
    skipped=$(echo "$total" | sed -n 's|.*, \([0-9]*\) skipped.*|, \1 skipped|p')
    printf '%s' "$score$skipped"
}

echo "running the cartridge on every implementation the README quotes" >&2

for model in dmg mgb cgbE agb; do
    "$HERE/tools/run-sameboy.sh" "$model" "$FRAMES" > "$TMP/sameboy-$model.txt"
done
"$HERE/tools/run-peanut.sh" "$FRAMES" > "$TMP/peanut.txt"
for mode in identical standard; do
    "$HERE/tools/run-terminalgb.sh" "$mode" 2000 "$TMP/terminalgb-$mode.txt"
done

ref() {  # ref <script> <variable>
    sed -n "s|^$2=\"\${$2:-\(.*\)}\"|\1|p" "$HERE/tools/$1" | cut -c1-7
}

cat > "$TMP/scoreboard.md" <<EOF
<!-- Generated by tools/scoreboard.sh. Do not edit by hand. -->
# The scoreboard

Measured $(date -u +%Y-%m-%d) by running \`dist/gbselftest.gb\` on each of these and
reading the report off the link port. Reproduce it with \`tools/scoreboard.sh\`;
every runner fetches and pins its own emulator, and none of them is vendored here.

<!-- table -->
| implementation | result |
|---|---:|
| SameBoy, DMG | $(row "$TMP/sameboy-dmg.txt") |
| SameBoy, MGB (Pocket) | $(row "$TMP/sameboy-mgb.txt") |
| SameBoy, CGB-E | $(row "$TMP/sameboy-cgbE.txt") |
| SameBoy, AGB | $(row "$TMP/sameboy-agb.txt") |
| TerminalGB, per-dot renderer | $(row "$TMP/terminalgb-identical.txt") |
| TerminalGB, whole-scanline renderer | $(row "$TMP/terminalgb-standard.txt") |
| Peanut-GB | $(row "$TMP/peanut.txt") |
<!-- /table -->

Revisions measured: SameBoy \`$(ref run-sameboy.sh SAMEBOY_COMMIT)\`, TerminalGB
\`$(ref run-terminalgb.sh TERMINALGB_REF)\`, Peanut-GB
\`$(ref run-peanut.sh PEANUT_REF)\`; the cartridge built with the RGBDS pinned in
\`tools/fetch-rgbds.sh\`.

A skip is not a pass, and it is not a failure either, and there are two kinds
here. Two checks REPORT rather than judge, because no published reference
settles what the right answer is: they print the number they saw and leave the
verdict to a reader who has hardware. The rest are rules that do not apply to
the console in the slot -- a defect that exists only in the original silicon, a
rule the cartridge has no second independent way to measure on a Color machine,
one handover state no published table covers for a monochrome cartridge in
compatibility mode, and one question about the transfer's address bus that a
monochrome console's memory map never raises. Each prints its own reason in the
run, so a skipped row is never silent.
EOF

if [ "$WRITE" -eq 0 ]; then
    cat "$TMP/scoreboard.md"
    exit 0
fi

cp "$TMP/scoreboard.md" "$HERE/docs/scoreboard.md"
echo "wrote docs/scoreboard.md" >&2

# The README quotes the same table between markers. Splicing it in here is what
# lets tools/check-readme.py insist the two agree: a table anybody can edit by
# hand is a table that will eventually be wrong.
python3 "$HERE/tools/splice-scoreboard.py" "$HERE/docs/scoreboard.md" \
    "$HERE/README.md" >&2
